apiVersion: v1
kind: Pod
metadata:
  name: cndw2025-demo-app
  labels:
    app: cndw2025-demo-app
spec:
  containers:
  - name: app
    image: ghcr.io/mochizuki875/cndw2025-demo-app:v1
    imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: cndw2025-demo-app
  labels:
    app: cndw2025-demo-app
spec:
  selector:
    app: cndw2025-demo-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080