name: Reusable Container Image Build Workflow

on:
  workflow_call:
    inputs:
      image-registry:
        description: 'Container registry URL'
        required: true
        type: string
      image-name:
        description: 'Container image name'
        required: true
        type: string
    secrets:
      ghcr_username:
        description: 'GitHub username for authentication'
        required: true
      ghcr_password:
        description: 'GitHub token for authentication'
        required: true
    outputs:
      image-digest:
        description: 'Built container image digest'
        value: ${{ jobs.publish.outputs.image-digest }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.image-registry }}
          username: ${{ secrets.ghcr_username }}
          password: ${{ secrets.ghcr_password }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image-registry }}/${{ inputs.image-name }}
      - name: Build and push Container image
        id: build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: false
